---
abstract: 'You cannot throw Chuck Norris'
author:
  - 'Hideaki Ohno <default {at} example.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-ChuckNorrisException
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Acme::ChuckNorris: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: origin
version: 0.01
